# CodeBuild BuildSpec file, this will install all the tools needed to deploy the app

version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      java: corretto11
      python: 3.9
    commands:
      - pip install git-remote-codecommit
      - docker pull mysql:5.7

  pre_build:
    commands:
      - curl -X POST -d "{'text':'[TEST-RUNNER] [$(date +"%H:%M:%S") UTC] - Started by \`$CODEBUILD_INITIATOR\`'}" "$SLACK_WEBHOOK_URL"
      - export MAVEN_CONFIG=''
      - export _JAVA_OPTIONS=-Xmx12g
      - export ROOT_DIR=$PWD
      - git checkout $BRANCH
      - sed -i "s|git@github.com:|https://github.com/|g" .gitmodules
      - sed -i 's|ssh://git-codecommit.|codecommit::|g;s|.amazonaws.*/|://|g' .gitmodules
      - git config --global --add protocol.codecommit.allow always
      - cd ..
      - git clone git@github.com:ensolvers/ensolvers-cicd.git
      - cp ensolvers-cicd/run-backend-tests.sh ensolvers-core/run-backend-tests.sh
      - cd $ROOT_DIR

    finally:
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 0 ]; then
          curl -X POST -d "{'text':':alert-red: [TEST-RUNNER] - AN ERROR OCCURRED DURING \`PRE_BUILD\` PHASE :alert-red:'}" "$SLACK_WEBHOOK_URL"
        fi

  build:
    commands:
      - bash ./ensolvers-core/run-backend-tests.sh "$MODULE_DIR"/src/test/resources/application.properties "$MODULE_DIR"/target/surefire-reports $PACKAGE_NAME $SONAR_TOKEN $SONAR_PROJECT_KEY

cache:
  paths:
    - '/root/.m2/**/*'